CREATE TABLE IF NOT EXISTS "aed" (
	"id" integer PRIMARY KEY NOT NULL,
	"location" json,
	"location_type" text,
	"availabilityRules" json,
	"availabilityDetails" text,
	"slug" text,
	"title" text,
	"created" text,
	"modified" text,
	"userEmail" text,
	"userName" text,
	"address" text,
	"postalCode" text,
	"city" text,
	"contactPerson" text,
	"phoneNumber" text,
	"addressDetails" text,
	"disclaimers" json
);
